# yaml-language-server: $schema=../../app-standard-v3.yml

version: 3
metadata:
  category: Payments
  name: BitcartCC
  version: 0.6.5.1
  tagline: BitcartCC is a self-hosted payment processor and developer solutions
    platform for cryptocurrencies
  description: BitcartCC provides light-weight, but secure and easy-to-use
    solutions for merchants and developers
  developers:
    BitcartCC: https://bitcartcc.com
  repo: https://github.com/bitcartcc/bitcart
  support: https://bitcartcc.com/#community
  gallery:
    - 1.png
    - 2.png
    - 3.png
containers:
  - name: admin
    restart: unless-stopped
    image: bitcartcc/bitcart-admin:stable
    command: yarn start
    environment:
      BITCART_ADMIN_LOG_FILE: bitcart.log
      BITCART_ADMIN_API_URL: http://$APP_BITCARTCC_BACKEND_IP:8000
  - name: backend
    depends_on:
      - bitcoin
      - database
      - redis
    restart: unless-stopped
    image: bitcartcc/bitcart:stable
    entrypoint: /usr/local/bin/docker-entrypoint.sh
    command: bash -c "alembic upgrade head && gunicorn -c gunicorn.conf.py main:app"
    environment:
      IN_DOCKER: false
      LOG_FILE: bitcart.log
      BITCART_DATADIR: /datadir
      BTC_NETWORK: $BITCOIN_NETWORK
      BTC_LIGHTNING: true
      REDIS_HOST: redis://$APP_BITCARTCC_REDIS_IP
      DB_HOST: $APP_BITCARTCC_DATABASE_IP
    user: 1000:1000
    data:
      - data/bitcart:/datadir
  - name: bitcoin
    restart: unless-stopped
    image: bitcartcc/bitcart-btc:stable
    environment:
      BTC_NETWORK: $BITCOIN_NETWORK
      BTC_LIGHTNING: true
      IN_DOCKER: false
    data:
      - data/bitcoin:/data
  - name: database
    restart: unless-stopped
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: bitcart
      POSTGRES_HOST_AUTH_METHOD: trust
    data:
      - data/postgres:/var/lib/postgresql/data
  - name: redis
    restart: unless-stopped
    image: redis:alpine
  - name: store
    restart: unless-stopped
    image: bitcartcc/bitcart-store:stable
    command: yarn start
    environment:
      BITCART_STORE_API_URL: http://$APP_BITCARTCC_BACKEND_IP:8000
  - name: worker
    depends_on:
      - backend
    restart: unless-stopped
    image: bitcartcc/bitcart:stable
    entrypoint: /usr/local/bin/docker-entrypoint.sh
    command: python3 worker.py
    environment:
      IN_DOCKER: false
      LOG_FILE: bitcart.log
      BITCART_DATADIR: /datadir
      BTC_NETWORK: $BITCOIN_NETWORK
      BTC_LIGHTNING: true
      REDIS_HOST: redis://$APP_BITCARTCC_REDIS_IP
      DB_HOST: $APP_BITCARTCC_DATABASE_IP
    user: 1000:1000
    data:
      - data/bitcart:/datadir
  - image: nginx:1.21.3-alpine@sha256:1ff1364a1c4332341fc0a854820f1d50e90e11bb0b93eb53b47dc5e10c680116
    init: true
    port: 80
    name: main
    data:
      - nginx/nginx.conf:/etc/nginx/nginx.conf
