# SPDX-FileCopyrightText: 2021 Citadel and contributors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# yaml-language-server: $schema=../../app-standard-v2.json

version: 2
metadata:
  category: Development
  name: code-server
  version: 4.3.0
  tagline: Run VS Code on your Citadel
  description: This app doesn't  have a description yet.
  developer: Coder
  website: https://coder.com
  dependencies: []
  repo: https://github.com/cdr/code-server
  support: https://github.com/cdr/code-server/discussions
  gallery:
    - 1.jpg
    - 2.jpg
    - 3.jpg
  defaultPassword: $APP_SEED
containers:
  - name: server
    image: codercom/code-server:4.3.0@sha256:9337ea40035a7c75f5ead93badb541d135cfa6bca9ca7af35ec39b8e4f407056
    user: 1000:1000
    environment:
      PASSWORD: $APP_SEED
    data:
      - data:/home/coder
