# SPDX-FileCopyrightText: Citadel and contributors
#
# SPDX-License-Identifier: AGPL-3.0-only

# yaml-language-server: $schema=../../app-standard-v3.yml

version: 3
metadata:
  category: Lightning Node Management
  name: Ride The Lightning
  version: 0.13.0
  tagline: Manage lightning node operations better
  description: Haven't written a desription yet for this, sorry.
  developers:
    Shahana and Suheb: ridethelightning.info
  dependencies:
    - - lnd
      - c-lightning
    - bitcoind
  repo: https://github.com/Ride-The-Lightning/RTL
  support: https://twitter.com/RTL_App
  gallery:
    - 1.jpg
    - 2.jpg
    - 3.jpg
  defaultPassword: $APP_SEED
containers:
  - name: main-lnd
    image: shahanafarooqui/rtl:0.13.0@sha256:65f0ba6a978bcf26c0e43a86c256abac1d8bfda80016327880b1dec2d39c538b
    user: 1000:1000
    port: 3000
    environment:
      PORT: 3000
      RTL_CONFIG_PATH: /data
      CHANNEL_BACKUP_PATH: /data/backup
      LN_IMPLEMENTATION: LND
      LN_SERVER_URL: https://$LND_IP:$LND_REST_PORT
      MACAROON_PATH: /lnd/data/chain/bitcoin/$BITCOIN_NETWORK
      CONFIG_PATH: /lnd/lnd.conf
      SWAP_SERVER_URL: https://$APP_RIDE_THE_LIGHTNING_LOOP_IP:8081
      SWAP_MACAROON_PATH: /loop/.loop/$BITCOIN_NETWORK
      BOLTZ_SERVER_URL: https://$APP_RIDE_THE_LIGHTNING_BOLTZ_IP:9003
      BOLTZ_MACAROON_PATH: /boltz/.boltz-lnd/macaroons
      APP_PASSWORD: $APP_SEED
    data:
      - loop:/loop
      - boltz:/boltz
      - rtl:/data
    requires:
      - lnd
  - name: loop
    image: ghcr.io/runcitadel/loop:v0.17.0-beta@sha256:be434e96905e8bc158e13b46b2e425ff140b04218286c11bf8124e1a8f65e2a1
    user: 1000:1000
    environment:
      HOME: /data
    command:
      - --network=$BITCOIN_NETWORK
      - --lnd.host="$LND_IP:$LND_GRPC_PORT"
      - --lnd.macaroonpath="/lnd/data/chain/bitcoin/$BITCOIN_NETWORK/admin.macaroon"
      - --lnd.tlspath="/lnd/tls.cert"
      - --restlisten=0.0.0.0:8081
    data:
      - loop:/data
    requires:
      - lnd
  - name: boltz
    image: boltz/boltz-lnd:1.2.6@sha256:01a56dd357a2460bfd0ecdd726d6db3ab59d78ee691250831d09ba5de3fec7ce
    user: 1000:1000
    restart: on-failure
    environment:
      HOME: /data
    data:
      - boltz:/data
    command:
      - --lnd.host="$LND_IP"
      - --lnd.macaroon="/lnd/data/chain/bitcoin/$BITCOIN_NETWORK/admin.macaroon"
      - --lnd.certificate="/lnd/tls.cert"
      - --rpc.rest.host="$APP_RIDE_THE_LIGHTNING_BOLTZ_IP"
      - --rpc.rest.port="9003"
    requires:
      - lnd
  - name: main-cln
    image: shahanafarooqui/rtl:0.12.2@sha256:049df155cc7bb0ad5554b16eda6c3c9703001c76d83a4b6b55d68ba89fba0de2
    user: 1000:1000
    port: 3000
    environment:
      PORT: 3000
      RTL_CONFIG_PATH: /data
      CHANNEL_BACKUP_PATH: /data/backup
      LN_IMPLEMENTATION: CLT
      LN_SERVER_URL: https://$C_LIGHTNING_IP:3001
      MACAROON_PATH: /c-lightning/certs
      CONFIG_PATH: /c-lightning/config
      APP_PASSWORD: $APP_SEED
    data:
      - rtl:/data
    requires:
      - c-lightning
