# SPDX-FileCopyrightText: Citadel and contributors
#
# SPDX-License-Identifier: AGPL-3.0-only

# yaml-language-server: $schema=../../app-standard-v2.json

version: 2
metadata:
  category: C-Lightning
  name: Ride The C-Lightning
  version: 0.12.2
  tagline: RTL with c-lightning (WIP)
  description: This app allows you to test the c-lightning integration on Citadel.
  developer: Shahana and Suheb
  website: ridethelightning.info
  dependencies:
    - c-lightning
    - bitcoind
  repo: https://github.com/Ride-The-Lightning/RTL
  support: https://twitter.com/RTL_App
  gallery:
    - 1.jpg
    - 2.jpg
    - 3.jpg
  defaultPassword: $APP_SEED
containers:
  - image: shahanafarooqui/rtl:0.12.2@sha256:049df155cc7bb0ad5554b16eda6c3c9703001c76d83a4b6b55d68ba89fba0de2
    user: 1000:1000
    port: 3000
    environment:
      PORT: 3000
      RTL_CONFIG_PATH: /data
      CHANNEL_BACKUP_PATH: /data/backup
      LN_IMPLEMENTATION: CLT
      LN_SERVER_URL: https://$C_LIGHTNING_IP:3001
      MACAROON_PATH: /c-lightning/certs
      CONFIG_PATH: /c-lightning/config
      APP_PASSWORD: $APP_SEED
    name: web
    data:
      - rtl:/data
    permissions:
      - c-lightning
      - bitcoind
