# SPDX-FileCopyrightText: 2021 Citadel and contributors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# yaml-language-server: $schema=../../app-standard-v3.yml

version: 3

metadata:
  category: Payments
  name: BTCPay Server
  version: 1.4.9
  tagline: Accept Bitcoin payments. Free, open-source & self-hosted, Bitcoin
    payment processor.
  description: "BTCPay Server is a free and open-source Bitcoin payment processor
    which allows you to accept bitcoin without fees or intermediaries. "
  developers: 
    BTCPay Server Foundation: https://btcpayserver.org
  dependencies:
    - lnd
    - bitcoind
  repo: https://github.com/btcpayserver/btcpayserver
  support: https://chat.btcpayserver.org
  gallery:
    - 1.jpg
    - 2.jpg
    - 3.jpg
containers:
  - name: nbxplorer
    image: nicolasdorier/nbxplorer:2.3.19@sha256:f12c8fddef6a8a1faf2ad16e0b0e0120e85520695f6b6c2dd55d61461dce0bb6
    user: 1000:1000
    environment:
      NBXPLORER_DATADIR: /data
      NBXPLORER_NETWORK: $BITCOIN_NETWORK
      NBXPLORER_PORT: 32838
      NBXPLORER_BIND: 0.0.0.0
      NBXPLORER_CHAINS: btc
      NBXPLORER_SIGNALFILEDIR: /data
      NBXPLORER_BTCRPCURL: http://$BITCOIN_IP:$BITCOIN_RPC_PORT
      NBXPLORER_BTCNODEENDPOINT: $BITCOIN_IP:$BITCOIN_P2P_PORT
      NBXPLORER_BTCRPCUSER: $BITCOIN_RPC_USER
      NBXPLORER_BTCRPCPASSWORD: $BITCOIN_RPC_PASS
    data:
      - data/nbxplorer:/data

  - name: main
    image: btcpayserver/btcpayserver:1.4.9@sha256:3310ef8c5fecb3a1c66507b97ebc84a3475fc77e63cd3bd29ab8b76474214566
    depends_on:
      - nbxplorer
      - postgres
    entrypoint:
      - dotnet
      - BTCPayServer.dll
    environment:
      HOME: /data
      BTCPAY_DATADIR: /data
      BTCPAY_PLUGINDIR: /data/plugins
      BTCPAY_DOCKERDEPLOYMENT: "false"
      BTCPAY_POSTGRES: User
        ID=postgres;Host=$APP_BTCPAY_SERVER_POSTGRES_IP;Port=5432;Database=btcpayserver$BITCOIN_NETWORK
      BTCPAY_NETWORK: $BITCOIN_NETWORK
      BTCPAY_BIND: 0.0.0.0:$APP_BTCPAY_SERVER_MAIN_PORT
      BTCPAY_CHAINS: btc
      BTCPAY_BTCEXPLORERURL: http://$APP_BTCPAY_SERVER_NBXPLORER_IP:32838
      BTCPAY_BTCLIGHTNING: type=lnd-rest;server=https://$LND_IP:$LND_REST_PORT/;macaroonfilepath=/lnd/data/chain/bitcoin/$BITCOIN_NETWORK/admin.macaroon;allowinsecure=true
      BTCPAY_SOCKSENDPOINT: $TOR_PROXY_IP:$TOR_PROXY_PORT
    data:
      - data/nbxplorer:/data/.nbxplorer
      - data/btcpay:/data
    user: 1000:1000

  - name: postgres
    image: ghcr.io/runcitadel/postgres:main@sha256:dae0ad86c75ef738203dda98e93b01a8c30923023a156caf7770e3c11242fcd2
    user: 1000:1000
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    data:
      - data/postgres:/var/lib/postgresql/data
