# yaml-language-server: $schema=../../app-standard-v4.yml

citadel_version: 4

metadata:
  name: Electrs
  version: 0.9.9
  category: Electrum Servers
  tagline: Lightweight Electrum server
  developers:
    Roman Zeyde: https://github.com/romanz
  permissions:
    - bitcoind
  repo:
    Electrs: https://github.com/romanz/electrs
    Container: https://github.com/runcitadel/docker-electrs
  support: https://t.me/runcitadel/
  gallery:
  - 1.jpg
  - 2.jpg
  - 3.jpg
  description: |-
    Electrs is a lightweight Electrum server for personal use.
    
    It's slower than Fulcrum, but uses less CPU, RAM and disk space.
  implements: electrum

services:
  main:
    image: nginx:1.21.6@sha256:2834dc507516af02784808c5f48b7cbe38b8ed5d0f4837f16e78d00deb7e7767
    init: true
    port: 80
    mounts:
      data:
        nginx/snowflake: /var/www/snowflake
        nginx/nginx.conf: /etc/nginx/nginx.conf

  service:
    image: ghcr.io/runcitadel/electrs:v0.9.9@sha256:9751e0d16130cab592dc18ddf2677300600c51843a86bb677821df912d532d52
    working_dir: /data
    mounts:
      bitcoin: /bitcoin
      data:
        data: /data
        electrs.toml: /data/electrs.toml
    restart: on-failure
    stop_grace_period: 5m
    required_ports:
      tcp:
        50001: 50001
    hidden_services:
      50001: 50001
