# SPDX-FileCopyrightText: 2021 Aaron Dewes <aaron.dewes@protonmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-only

# yaml-language-server: $schema=../../app-standard-v3.yml

version: 3
metadata:
  category: Explorers
  name: Bitfeed
  version: 2.2.1
  tagline: A live visualization of your node's mempool
  description: A self-hosted version of Bitfeed - the open source mempool & block
    visualizer available at https://bits.monospace.live. Watch as new
    transactions drop into your node's mempool, before being packaged into newly
    mined blocks. Monitor Bitcoin network activity, explore the composition of
    the latest block, or simply enjoy a soothing Bitcoin screensaver.
  developers: 
    Mononaut: https://monospace.live
  dependencies:
    - bitcoind
  repo: https://github.com/bitfeed-project/bitfeed
  support: https://github.com/bitfeed-project/bitfeed/issues
  gallery:
    - 1.jpg
    - 2.jpg
    - 3.jpg
  updateContainer:
    - main
    - api

containers:
  - name: main
    image: ghcr.io/bitfeed-project/bitfeed-client:v2.2.1@sha256:70c89d49d20ba3da21c648c259f45a4b89e06bfe1d97374a092dce6f891d03c6
    restart: on-failure
    stop_grace_period: 1m
    port: 80
    depends_on:
      - api
    environment:
      TARGET: citadel
      BACKEND_HOST: $APP_BITFEED_API_IP
      BACKEND_PORT: "3000"

  - name: api
    image: ghcr.io/bitfeed-project/bitfeed-server:v2.2.1@sha256:60eae8109d3d6a377aec8a954f93b6be9ee48de717c9ab5810c2a5afcf688554
    user: 1000:1000
    restart: on-failure
    stop_grace_period: 1m
    environment:
      PORT: "3000"
      BITCOIN_HOST: $BITCOIN_IP
      BITCOIN_ZMQ_RAWTX_PORT: $BITCOIN_ZMQ_RAWTX_PORT
      BITCOIN_ZMQ_RAWBLOCK_PORT: $BITCOIN_ZMQ_RAWBLOCK_PORT
      BITCOIN_ZMQ_SEQUENCE_PORT: $BITCOIN_ZMQ_SEQUENCE_PORT
      BITCOIN_RPC_PORT: $BITCOIN_RPC_PORT
      BITCOIN_RPC_USER: $BITCOIN_RPC_USER
      BITCOIN_RPC_PASS: $BITCOIN_RPC_PASS
      RPC_POOLS: 3
      RPC_POOL_SIZE: 4
    data:
      - data:/app/data
