citadel_version: 4
metadata:
  name: Fulcrum
  version: 1.8.1
  category: Electrum Servers
  tagline: Fast Electrum server
  developers:
    Calin Culianu: https://github.com/cculianu/Fulcrum
  description: Fulcrum is a very fast Electrum server. While it's faster than Electrs, it uses more CPU, RAM and disk space.
  permissions:
  - bitcoind
  repo:
    Public: https://github.com/cculianu/Fulcrum
  support: https://t.me/runcitadel
  gallery:
  - 1.jpg
  - 2.jpg
  - 3.jpg
  defaultPassword: null
  torOnly: false
  implements: electrum
services:
  service:
    image: cculianu/fulcrum:latest@sha256:c0543f8b8a5bf6b0c447d8525d6b4360a6c07532f7741f19cc2c179968e71848
    stop_grace_period: 5m
    restart: on-failure
    command: /usr/bin/Fulcrum /data/fulcrum.conf
    mounts:
      data:
        data: /data
        fulcrum.conf: /data/fulcrum.conf
    required_ports:
      tcp:
        50001: 50001
        50003: 50003
  main:
    image: nginx:1.8.1@sha256:9b3e9f189890ef9d6713c3384da3809731bdb0bff84e7b68da330ebadf533085
    init: true
    port: 80
    mounts:
      data:
        nginx/snowflake: /var/www/snowflake
        nginx/nginx.conf: /etc/nginx/nginx.conf
