citadel_version: 4
metadata:
  name: WordPress
  version: 6.0.2
  category: Blog
  tagline: Host a blog on your Citadel
  developers:
    WordPress Developers: https://wordpress.org
  description: WordPress
  permissions: []
  repo:
    WordPress: https://github.com/WordPress/WordPress
    Container: https://github.com/docker-library/wordpress
  support: https://wordpress.org
  gallery:
  - 1.png
  - 2.png
  - 3.png
  defaultPassword: null
  torOnly: false
services:
  main:
    image: wordpress:6.0.2@sha256:3dff5e9e1497b522b48dd8a0fcf50dfbbb925f1487c6db581c28e73fdbfc49c1
    depends_on:
    - db
    restart: always
    environment:
      WORDPRESS_CONFIG_EXTRA: |
        define('FS_METHOD','direct');
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: somewordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_HOST: $APP_WORDPRESS_DB_IP
    port: 80
  db:
    image: mariadb:10.7.3-focal@sha256:07e06f2e7ae9dfc63707a83130a62e00167c827f08fcac7a9aa33f4b6dc34e0e
    user: 1000:1000
    restart: always
    environment:
      MARIADB_PASSWORD: wordpress
      MARIADB_DATABASE: wordpress
      MARIADB_USER: wordpress
      MARIADB_ROOT_PASSWORD: somewordpress
    mounts:
      data:
        data/db: /var/lib/mysql
